version: '3.8'

services:
  site-iadmin:
    build: .
    container_name: site-iadmin
    restart: always
    networks:
      - traefik_public
    labels:
      - traefik.enable=true
      - traefik.http.routers.site.rule=Host(`iadmin.app`)
      - traefik.http.routers.site.entrypoints=websecure
      - traefik.http.routers.site.tls.certresolver=le
      - traefik.http.services.site.loadbalancer.server.port=80

networks:
  traefik_public:
    external: true
