version: '3.8'

services:
  site-iadmin:
    image: romulomorgan/site-iadmin:latest  # <-- use sua imagem já construída e enviada para Docker Hub
    networks:
      - traefik_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.site.rule=Host(`iadmin.app`)
        - traefik.http.routers.site.entrypoints=websecure
        - traefik.http.routers.site.tls.certresolver=le
        - traefik.http.services.site.loadbalancer.server.port=80

networks:
  traefik_public:
    external: true
