// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbbuamqyfrvsybfqkebj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiYnVhbXF5ZnJ2c3liZnFrZWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MDUwODEsImV4cCI6MjA1NDA4MTA4MX0.Ydo3JZn0qWsTwGZtS26KhxESKvcSzlysIcQk4fAdZm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);